package com.flexsentlabs.koncerto.deploy

import com.flexsentlabs.koncerto.logging.StructuredLogger
import java.util.concurrent.TimeUnit

class DemoFailureReporter(
    private val logger: StructuredLogger
) {
    fun postFailure(prNumber: Int, repoFullName: String, error: String, logs: String?) {
        val body = buildString {
            appendLine("## Demo Recording Failed")
            appendLine()
            appendLine("**Reason:** $error")
            if (logs != null) {
                appendLine()
                appendLine("<details>")
                appendLine("<summary>Container Logs</summary>")
                appendLine()
                appendLine("```")
                appendLine(logs.take(5000))
                appendLine("```")
                appendLine("</details>")
            }
            appendLine()
            appendLine("---")
            appendLine("_Auto-generated by koncerto_")
        }

        try {
            val pb = ProcessBuilder(
                "gh", "pr", "comment", prNumber.toString(),
                "--repo", repoFullName,
                "--body", body
            )
            val p = pb.start()
            val completed = p.waitFor(10, TimeUnit.SECONDS)
            val output = p.inputStream.bufferedReader().use { it.readText() }
            if (!completed) {
                p.destroyForcibly()
                logger.warn("demo_failure_comment_timed_out", mapOf("pr" to prNumber.toString()))
            } else if (p.exitValue() == 0) {
                logger.info("demo_failure_comment_posted", mapOf("pr" to prNumber.toString()))
            } else {
                logger.warn("demo_failure_comment_failed", mapOf("output" to output.take(200)))
            }
        } catch (e: Exception) {
            logger.warn("demo_failure_comment_error", mapOf("pr" to prNumber.toString()),
                "error" to (e.message ?: "unknown"))
        }
    }
}
