package com.flexsentlabs.koncerto.metrics

import io.micrometer.core.instrument.Gauge
import io.micrometer.core.instrument.MeterRegistry
import io.micrometer.core.instrument.binder.MeterBinder
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import java.util.concurrent.atomic.AtomicReference
import java.util.function.Supplier

class PrometheusMetricsBinder(
    private val metricsRepository: MetricsRepository,
    private val quotaRemainingSuppliers: Map<String, Supplier<Double>> = emptyMap(),
    refreshIntervalMs: Long = 15_000L
) : MeterBinder {

    private val cache = AtomicReference<List<IssueMetrics>>(emptyList())
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    init {
        scope.launch {
            while (true) {
                try { cache.set(metricsRepository.findAll()) } catch (_: Exception) {}
                delay(refreshIntervalMs)
            }
        }
    }

    override fun bindTo(registry: MeterRegistry) {
        bindTotalRuns(registry)
        bindTotalTokens(registry)
        bindRunsByProject(registry)
        bindRunsByState(registry)
        bindQuotaRemaining(registry)
    }

    private fun bindTotalRuns(registry: MeterRegistry) {
        Gauge.builder("koncerto_agent_runs_total", cache) { c ->
            c.get().sumOf { it.totalRuns }.toDouble()
        }.description("Total number of agent runs across all issues")
            .tag("type", "total")
            .register(registry)
    }

    private fun bindTotalTokens(registry: MeterRegistry) {
        Gauge.builder("koncerto_agent_tokens_total", cache) { c ->
            c.get().sumOf { it.totalInputTokens }.toDouble()
        }.description("Total input tokens consumed by agent runs")
            .tag("type", "input")
            .register(registry)

        Gauge.builder("koncerto_agent_tokens_total", cache) { c ->
            c.get().sumOf { it.totalOutputTokens }.toDouble()
        }.description("Total output tokens generated by agent runs")
            .tag("type", "output")
            .register(registry)

        Gauge.builder("koncerto_agent_tokens_total", cache) { c ->
            c.get().sumOf { it.totalTokens }.toDouble()
        }.description("Total tokens (input + output) for agent runs")
            .tag("type", "total")
            .register(registry)
    }

    private fun bindRunsByProject(registry: MeterRegistry) {
        val snapshot = cache.get()
        snapshot.filter { it.projectSlug != null }
            .groupBy { it.projectSlug!! }
            .forEach { (project, metrics) ->
                val count = metrics.sumOf { it.totalRuns }
                Gauge.builder("koncerto_agent_runs_by_project", Supplier { count.toDouble() })
                    .description("Total agent runs for project")
                    .tag("project", project)
                    .register(registry)
            }
    }

    private fun bindRunsByState(registry: MeterRegistry) {
        val snapshot = cache.get()
        snapshot.filter { it.lastResult != null }
            .groupBy { it.lastResult!! }
            .forEach { (state, metrics) ->
                val count = metrics.sumOf { it.totalRuns }
                Gauge.builder("koncerto_agent_runs_by_state", Supplier { count.toDouble() })
                    .description("Total agent runs for state")
                    .tag("state", state)
                    .register(registry)
            }
    }

    private fun bindQuotaRemaining(registry: MeterRegistry) {
        for ((project, supplier) in quotaRemainingSuppliers) {
            Gauge.builder("koncerto_quota_remaining", supplier) { supplier.get() }
                .description("Remaining quota capacity for project")
                .tag("project", project)
                .register(registry)
        }
    }
}
