package com.flexsentlabs.koncerto.metrics

import io.micrometer.core.instrument.Gauge
import io.micrometer.core.instrument.MeterRegistry
import io.micrometer.core.instrument.binder.MeterBinder
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import java.util.function.Supplier

class PrometheusMetricsBinder(
    private val metricsRepository: SqliteMetricsRepository,
    private val quotaRemainingSuppliers: Map<String, Supplier<Double>> = emptyMap()
) : MeterBinder {

    override fun bindTo(registry: MeterRegistry) {
        bindTotalRuns(registry)
        bindTotalTokens(registry)
        bindRunsByProject(registry)
        bindRunsByState(registry)
        bindQuotaRemaining(registry)
    }

    private fun bindTotalRuns(registry: MeterRegistry) {
        Gauge.builder("koncerto_agent_runs_total", this) { binder ->
            runBlocking(Dispatchers.IO) {
                val allRuns = binder.metricsRepository.findAll()
                allRuns.sumOf { it.totalRuns }.toDouble()
            }
        }.description("Total number of agent runs across all issues")
            .tag("type", "total")
            .register(registry)
    }

    private fun bindTotalTokens(registry: MeterRegistry) {
        Gauge.builder("koncerto_agent_tokens_total", this) { binder ->
            runBlocking(Dispatchers.IO) {
                val allRuns = binder.metricsRepository.findAll()
                allRuns.sumOf { it.totalInputTokens }.toDouble()
            }
        }.description("Total input tokens consumed by agent runs")
            .tag("type", "input")
            .register(registry)

        Gauge.builder("koncerto_agent_tokens_total", this) { binder ->
            runBlocking(Dispatchers.IO) {
                val allRuns = binder.metricsRepository.findAll()
                allRuns.sumOf { it.totalOutputTokens }.toDouble()
            }
        }.description("Total output tokens generated by agent runs")
            .tag("type", "output")
            .register(registry)

        Gauge.builder("koncerto_agent_tokens_total", this) { binder ->
            runBlocking(Dispatchers.IO) {
                val allRuns = binder.metricsRepository.findAll()
                allRuns.sumOf { it.totalTokens }.toDouble()
            }
        }.description("Total tokens (input + output) for agent runs")
            .tag("type", "total")
            .register(registry)
    }

    private fun bindRunsByProject(registry: MeterRegistry) {
        runBlocking(Dispatchers.IO) {
            val allRuns = metricsRepository.findAll()
            val runsByProject = allRuns
                .filter { it.projectSlug != null }
                .groupBy { it.projectSlug!! }
                .mapValues { (_, metrics) -> metrics.sumOf { it.totalRuns } }

            runsByProject.forEach { (project, count) ->
                Gauge.builder("koncerto_agent_runs_by_project", Supplier { count.toDouble() })
                    .description("Total agent runs for project")
                    .tag("project", project)
                    .register(registry)
            }
        }
    }

    private fun bindRunsByState(registry: MeterRegistry) {
        runBlocking(Dispatchers.IO) {
            val allRuns = metricsRepository.findAll()
            val runsByState = allRuns
                .filter { it.lastResult != null }
                .groupBy { it.lastResult!! }
                .mapValues { (_, metrics) -> metrics.sumOf { it.totalRuns } }

            runsByState.forEach { (state, count) ->
                Gauge.builder("koncerto_agent_runs_by_state", Supplier { count.toDouble() })
                    .description("Total agent runs for state")
                    .tag("state", state)
                    .register(registry)
            }
        }
    }

    private fun bindQuotaRemaining(registry: MeterRegistry) {
        for ((project, supplier) in quotaRemainingSuppliers) {
            Gauge.builder("koncerto_quota_remaining", supplier) { supplier.get() }
                .description("Remaining quota capacity for project")
                .tag("project", project)
                .register(registry)
        }
    }
}